const DEFAULTS=
[
["Aptitude","20% of 150 = ?",["20","30","25","35"],1],
["Aptitude","Series: 2, 6, 12, 20, 30, ?",["40","42","44","36"],1],
["Aptitude","Two numbers are in ratio 3:5 and sum to 160. The larger number is?",["60","80","100","90"],2],
["Aptitude","72 km/h in m/s = ?",["18","20","22","25"],1],
["Aptitude","Cost price ₹400, selling price ₹500. Profit % = ?",["20%","25%","30%","15%"],1],
["Aptitude","Odd one out:",["Cappuccino","Latte","Espresso","Croissant"],3],
["Aptitude","If CAT = 24 (A=1, B=2...), then DOG = ?",["24","25","26","28"],2],
["Aptitude","Simple interest on ₹1000 at 10% for 2 years?",["₹100","₹200","₹210","₹150"],1],
["Aptitude","A does a job in 10 days, B in 15 days. Together they take?",["5 days","6 days","7 days","8 days"],1],
["Aptitude","Average of 10, 20, 30, 40, 50 = ?",["25","30","35","40"],1],
["GK","Taj Mahal Palace, Mumbai opened in?",["1889","1903","1947","1911"],1],
["GK","Founder of the Tata Group and Taj Hotels?",["J.R.D. Tata","Ratan Tata","Jamsetji Tata","Dorabji Tata"],2],
["GK","Capital of Australia?",["Sydney","Melbourne","Canberra","Perth"],2],
["GK","Currency of Japan?",["Yuan","Yen","Won","Baht"],1],
["GK","Largest Indian state by area?",["Madhya Pradesh","Maharashtra","Rajasthan","Uttar Pradesh"],2],
["GK","Highest Michelin Guide rating for a restaurant?",["5 stars","3 stars","4 stars","10 points"],1],
["GK","World Tourism Day is observed on?",["27 September","5 June","1 May","21 March"],0],
["GK","India's tourism campaign 'Atithi Devo Bhava' means?",["Guest is God","Visit India","Serve with smile","Welcome home"],0],
["GK","Chandrayaan-3 landed near the Moon's?",["North pole","Equator","South pole","Far side centre"],2],
["GK","UN headquarters is in?",["Geneva","New York","Paris","Vienna"],1],
["Front Office","A guest without a prior booking is a?",["No-show","Walk-in","Skipper","Stayover"],1],
["Front Office","A guest who booked but neither arrived nor cancelled is a?",["Walk-in","No-show","Early departure","Scanty baggage"],1],
["Front Office","Occupancy % = ?",["Rooms sold ÷ rooms available × 100","Revenue ÷ rooms sold","Rooms vacant ÷ sold","Revenue ÷ available rooms"],0],
["Front Office","ADR (Average Daily Rate) = ?",["Room revenue ÷ rooms available","Room revenue ÷ rooms sold","Total revenue ÷ guests","Rooms sold ÷ revenue"],1],
["Front Office","RevPAR = ?",["Room revenue ÷ rooms sold","Room revenue ÷ rooms available","Rooms sold ÷ available","ADR ÷ 2"],1],
["Front Office","Rack rate means?",["Discounted rate","Corporate rate","Standard published rate","Group rate"],2],
["Front Office","Meal plan 'EP' (European Plan) includes?",["Room only","Room + breakfast","Room + 2 meals","Room + all meals"],0],
["Front Office","Meal plan 'MAP' includes?",["Room only","Room + breakfast","Room + breakfast + one main meal","Room + all meals"],2],
["Front Office","Meal plan 'AP' (American Plan) includes?",["Room only","Room + breakfast","Room + 2 meals","Room + all three meals"],3],
["Front Office","Guest leaves without settling the bill. He is a?",["Skipper","Walk-in","VIP","Stayover"],0],
["Front Office","Night audit is mainly done to?",["Clean rooms","Reconcile the day's transactions and close the day","Greet guests","Book events"],1],
["Front Office","Taking more confirmed bookings than available rooms is?",["Upselling","Overbooking","Blocking","Sleep-out"],1],
["Front Office","PMS in hotels stands for?",["Property Management System","Payment Maintenance Service","Personal Management Software","Primary Mail System"],0],
["Front Office","Which desk handles guest luggage?",["Concierge","Bell desk","Cashier","Reservations"],1],
["Front Office","Which form must be filled for foreign guests in India?",["Form A","Form B","Form C","Form D"],2],
["Front Office","A room status 'OOO' means?",["Occupied overnight","Out of order","Open on order","Occupied, ok"],1],
["Front Office","A twin room has?",["One double bed","Two single beds","One king bed","Bunk bed"],1],
["Front Office","The guest folio is?",["Room key","Record of guest's charges and payments","Guest ID","Welcome note"],1],
["Front Office","First step in handling a guest complaint?",["Defend the hotel","Listen attentively","Transfer to manager at once","Offer discount"],1],
["Front Office","Offering a higher-category room to increase revenue is?",["Upselling","Overbooking","Walk-in","Blocking"],0]
];